name: Deploy Dist

on:
  push:
    branches:
      - main
    paths-ignore:
      #- '.github/workflows/*'
      - 'README.md'
  workflow_dispatch:
 
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore GradeSolution.sln

      - name: Test
        run: dotnet test GradeSolution.sln -c Release

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore GradeSolution.sln

      - name: Build
        run: dotnet build GradeSolution.sln -c Release --no-restore

      - name: Upload GradeSolution Artifact
        uses: actions/upload-artifact@v4
        with:
          name: GradeSolution-files
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download GradeSolution Artifact
        uses: actions/download-artifact@v4
        with:
          name: GradeSolution-files
          path: .

      - name: Deploy
        run: echo "Deploy successful"
